### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by phar1no** [Graylog2/check-graylog2-stream#5]
What kind of graylog version do your plugin version 1.4 work?

```
[root@locahost]# ./check-graylog2-stream -stream=56eab50c1652906f7436c8a2 -url='https://someserver:443' -user=someuser -password=somepass
UNKNOWN: Can not parse JSON from Graylog2 API
```
My Graylog 2.2.3+7adc951

**Comment by mariussturm** [comment]
The stream api didn't change so it should work with your Graylog version.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
