### ISSUE TITLE
problems with aggregates Plugin

### ISSUE THREAD

**Issue by geosone** [Graylog2/check-graylog2-stream#6]
if the aggregates plugin (https://github.com/cvtienhoven/graylog-plugin-aggregates) is used on a stream the check will quit with
`UNKNOWN: Got wrong return code from Graylog2 API, please check all command line parameters`

even if you set the correct -condition id for the allert that you want to check is used.

**Comment by joschi** [comment]
@geosone Please provide the complete configuration of `check-graylog2-stream`, the version of the aggregates plugin you're using, and the complete logs of your Graylog node around the time the request is being sent and failed.

**Comment by geosone** [comment]
i have found the problem one user was using a check on full_message that was not defined as fielddata=true in the leasticsearch. so the output was wrong in the api.
